# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# Adeola
# https://aka.ms/yaml

trigger:
- none

resources:
  pipelines:
    - pipeline: buildContosoAir # identifier for the resource used in pipeline resource variables
      source: addydevbox.ContosoAir(1) # name of the pipeline that produces the artifact
      trigger:
        branches:
         include:
           - master

pool:
   vmImage: ubuntu-latest
  
steps:
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '8bfe8034-b2be-4501-92e0-264ddcd05585'
    definition: '70'
    buildVersionToDownload: 'latest'
    targetPath: '$(Pipeline.Workspace)'
    
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure Connection'
    subscriptionId: 'e0acda36-f565-462e-9a9b-bc00260e00c6'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourcegroup)'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: '$(Pipeline.Workspace)/drop/Templates/azuredeploy.json'
    csmParametersFile: '$(Pipeline.Workspace)/drop/Templates/azuredeploy.parameters.json'
    overrideParameters: '-p_environment $(web_environment) -p_site_prefix $(web_prefix) -p_site_web_name $(web_site)'
    deploymentMode: 'Incremental'
    
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure Connection'
    appType: 'webApp'
    WebAppName: 
    packageForLinux: '$(Pipeline.Workspace)/*/.zip.'